In [31]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("@1a23456Z7")  # your MySQL password

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/retailiq"
)

print(engine.url)

mysql+pymysql://root:***@localhost:3306/retailiq

In [32]:
import pandas as pd

pd.read_sql(
    "SELECT DATABASE() as current_db;",
    engine
)

  current_db
0   retailiq

In [33]:
import os

print(os.getcwd())

/Users/piyushisinghal/Downloads/RetailIQ/Python

In [34]:
import os

print(os.path.exists("../Dataset/customers.csv"))
print(os.path.exists("../Dataset/products.csv"))
print(os.path.exists("../Dataset/geography.csv"))
print(os.path.exists("../Dataset/orders.csv"))

True
True
True
True

In [35]:
import pandas as pd

customers = pd.read_csv("../Dataset/customers.csv")
products = pd.read_csv("../Dataset/products.csv")
geography = pd.read_csv("../Dataset/geography.csv")
orders = pd.read_csv("../Dataset/orders.csv")

In [36]:
print(customers.shape)
print(products.shape)
print(geography.shape)
print(orders.shape)

(2501, 4)
(1894, 4)
(632, 5)
(9994, 11)

In [38]:
customers.columns = [
    "customer_id",
    "customer_name",
    "segment",
    "region"
]

products.columns = [
    "product_id",
    "product_name",
    "category",
    "sub_category"
]

geography.columns = [
    "postal_code",
    "city",
    "state",
    "region",
    "country"
]

In [39]:
print(customers.columns.tolist())
print(products.columns.tolist())
print(geography.columns.tolist())

['customer_id', 'customer_name', 'segment', 'region']
['product_id', 'product_name', 'category', 'sub_category']
['postal_code', 'city', 'state', 'region', 'country']

In [43]:
customers.columns.tolist()

['customer_id', 'customer_name', 'segment', 'region']

In [44]:
customers["customer_id"].duplicated().sum()

np.int64(1708)

In [45]:
customers["customer_id"].nunique()

793

In [46]:
customers.shape

(2501, 4)

In [47]:
customers = customers.drop_duplicates(
    subset=["customer_id"]
)

In [48]:
print(customers.shape)

print(customers["customer_id"].nunique())

print(customers["customer_id"].duplicated().sum())

(793, 4)
793
0

In [49]:
customers.to_csv(
    "../Dataset/customers.csv",
    index=False
)

In [ ]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE customers"))
    conn.commit()

In [51]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("""
        CREATE TABLE customers(
            customer_id VARCHAR(20) PRIMARY KEY,
            customer_name VARCHAR(100),
            segment VARCHAR(50),
            region VARCHAR(50)
        )
    """))
    conn.commit()

In [52]:
customers = pd.read_csv("../Dataset/customers.csv")

customers.columns = [
    "customer_id",
    "customer_name",
    "segment",
    "region"
]

In [53]:
customers.to_sql(
    "customers",
    engine,
    if_exists="append",
    index=False
)

793

In [54]:
pd.read_sql(
    "SELECT COUNT(*) AS cnt FROM customers",
    engine
)

   cnt
0  793

In [55]:
products.columns = [
    "product_id",
    "product_name",
    "category",
    "sub_category"
]

print(products.shape)
print(products["product_id"].nunique())
print(products["product_id"].duplicated().sum())

(1894, 4)
1862
32

In [56]:
duplicate_products = products[
    products["product_id"].duplicated(keep=False)
].sort_values("product_id")

duplicate_products.head(20)

,product_id,product_name,category,sub_category
1364,FUR-BO-10002213,"Sauder Forest Hills Library, Woodland Oak Finish",Furniture,Bookcases
1259,FUR-BO-10002213,DMI Eclipse Executive Suite Bookcases,Furniture,Bookcases
64,FUR-CH-10001146,"Global Value Mid-Back Manager's Chair, Gray",Furniture,Chairs
124,FUR-CH-10001146,"Global Task Chair, Black",Furniture,Chairs
1010,FUR-FU-10001473,DAX Wood Document Frame,Furniture,Furnishings
1280,FUR-FU-10001473,"Eldon Executive Woodline II Desk Accessories, ...",Furniture,Furnishings
1614,FUR-FU-10004017,"Executive Impressions 13"" Chairman Wall Clock",Furniture,Furnishings
217,FUR-FU-10004017,Tenex Contemporary Contur Chairmats for Low an...,Furniture,Furnishings
978,FUR-FU-10004091,"Eldon 200 Class Desk Accessories, Black",Furniture,Furnishings
268,FUR-FU-10004091,"Howard Miller 13"" Diameter Goldtone Round Wall...",Furniture,Furnishings
1015,FUR-FU-10004270,"Eldon Image Series Desk Accessories, Burgundy",Furniture,Furnishings
1412,FUR-FU-10004270,"Executive Impressions 13"" Clairmont Wall Clock",Furniture,Furnishings
28,FUR-FU-10004848,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",Furniture,Furnishings
1338,FUR-FU-10004848,DAX Solid Wood Frames,Furniture,Furnishings
443,FUR-FU-10004864,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",Furniture,Furnishings
1760,FUR-FU-10004864,Eldon 500 Class Desk Accessories,Furniture,Furnishings
863,OFF-AP-10000576,"Belkin 325VA UPS Surge Protector, 6'",Office Supplies,Appliances
648,OFF-AP-10000576,Belkin 7 Outlet SurgeMaster II,Office Supplies,Appliances
1579,OFF-AR-10001149,Avery Hi-Liter Comfort Grip Fluorescent Highli...,Office Supplies,Art
131,OFF-AR-10001149,"Sanford Colorific Colored Pencils, 12/Box",Office Supplies,Art

In [57]:
duplicate_products.shape

(64, 4)

In [58]:
products = products.drop_duplicates(
    subset=["product_id"]
)

In [59]:
products.shape
products["product_id"].nunique()
products["product_id"].duplicated().sum()

np.int64(0)

In [61]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE products"))
    conn.commit()

OperationalError: (pymysql.err.OperationalError) (1051, "Unknown table 'retailiq.products'")
[SQL: DROP TABLE products]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [62]:
products = products.reset_index(drop=True)

products["product_key"] = products.index + 1

In [63]:
products.head()

,product_id,product_name,category,sub_category,product_key
0,FUR-BO-10001798,Bush Somerset Collection Bookcase,Furniture,Bookcases,1
1,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",Furniture,Chairs,2
2,OFF-LA-10000240,Self-Adhesive Address Labels for Typewriters b...,Office Supplies,Labels,3
3,FUR-TA-10000577,Bretford CR4500 Series Slim Rectangular Table,Furniture,Tables,4
4,OFF-ST-10000760,Eldon Fold 'N Roll Cart System,Office Supplies,Storage,5

In [64]:
products = products[
    [
        "product_key",
        "product_id",
        "product_name",
        "category",
        "sub_category"
    ]
]

In [65]:
with engine.connect() as conn:

    conn.execute(text("""
        CREATE TABLE products(
            product_key INT PRIMARY KEY,
            product_id VARCHAR(30),
            product_name VARCHAR(255),
            category VARCHAR(50),
            sub_category VARCHAR(50)
        )
    """))

    conn.commit()

In [66]:
products.columns = [
    "product_key",
    "product_id",
    "product_name",
    "category",
    "sub_category"
]

In [67]:
products.to_sql(
    "products",
    engine,
    if_exists="append",
    index=False
)

1862

In [68]:
pd.read_sql(
    "SELECT COUNT(*) as cnt FROM products",
    engine
)

    cnt
0  1862

In [69]:
products = pd.read_csv("../Dataset/products.csv")

print(products.shape)

(1894, 4)

In [70]:
pd.read_sql(
    "SELECT COUNT(*) AS cnt FROM products;",
    engine
)

    cnt
0  1862

In [71]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE products"))
    conn.commit()

print("Products table dropped")

Products table dropped

In [72]:
products = pd.read_csv("../Dataset/products.csv")

print(products.shape)

(1894, 4)

In [73]:
products = products.reset_index(drop=True)

products["product_key"] = products.index + 1

In [74]:
products = products[
    [
        "product_key",
        "Product ID",
        "Product Name",
        "Category",
        "Sub-Category"
    ]
]

In [75]:
products.columns = [
    "product_key",
    "product_id",
    "product_name",
    "category",
    "sub_category"
]

In [76]:
print(products.shape)
print(products["product_key"].nunique())

(1894, 5)
1894

In [77]:
with engine.connect() as conn:

    conn.execute(text("""
        CREATE TABLE products(
            product_key INT PRIMARY KEY,
            product_id VARCHAR(30),
            product_name VARCHAR(255),
            category VARCHAR(50),
            sub_category VARCHAR(50)
        )
    """))

    conn.commit()

In [78]:
products.to_sql(
    "products",
    engine,
    if_exists="append",
    index=False
)

1894

In [79]:
geography.columns = [
    "postal_code",
    "city",
    "state",
    "region",
    "country"
]

print("Rows:", geography.shape[0])
print("Unique Postal Codes:", geography["postal_code"].nunique())
print("Duplicate Postal Codes:", geography["postal_code"].duplicated().sum())

Rows: 632
Unique Postal Codes: 631
Duplicate Postal Codes: 1

In [90]:
geography[
    geography["postal_code"].duplicated(keep=False)
].sort_values("postal_code")

     postal_code       city       state region        country  geo_key
142        92024  San Diego  California   West  United States      143
235        92024  Encinitas  California   West  United States      236

In [91]:
geography = pd.read_csv("../Dataset/geography.csv")

In [92]:
geography = geography.reset_index(drop=True)

geography["geo_key"] = geography.index + 1

In [93]:
geography = geography[
    [
        "geo_key",
        "Postal Code",
        "City",
        "State",
        "Region",
        "Country"
    ]
]

In [94]:
geography.columns = [
    "geo_key",
    "postal_code",
    "city",
    "state",
    "region",
    "country"
]

In [95]:
print(geography.shape)
print(geography["geo_key"].nunique())

(632, 6)
632

In [96]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE geography"))
    conn.commit()

In [97]:
with engine.connect() as conn:

    conn.execute(text("""
        CREATE TABLE geography(
            geo_key INT PRIMARY KEY,
            postal_code INT,
            city VARCHAR(100),
            state VARCHAR(100),
            region VARCHAR(50),
            country VARCHAR(50)
        )
    """))

    conn.commit()

In [98]:
geography.to_sql(
    "geography",
    engine,
    if_exists="append",
    index=False
)

632

In [99]:
pd.read_sql(
    "SELECT COUNT(*) AS cnt FROM geography;",
    engine
)

   cnt
0  632

In [100]:
print(orders.shape)
print(orders.columns.tolist())

(9994, 11)
['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Product ID', 'Postal Code', 'Sales', 'Quantity', 'Discount', 'Profit']

In [101]:
from sqlalchemy import text

with engine.connect() as conn:

    conn.execute(text("""
        CREATE TABLE orders(
            order_line_id INT AUTO_INCREMENT PRIMARY KEY,

            order_id VARCHAR(30),

            order_date DATE,
            ship_date DATE,

            ship_mode VARCHAR(50),

            customer_id VARCHAR(20),

            product_id VARCHAR(30),

            postal_code INT,

            sales DECIMAL(12,2),

            quantity INT,

            discount DECIMAL(5,2),

            profit DECIMAL(12,2)
        )
    """))

    conn.commit()

In [102]:
orders.columns = [
    "order_id",
    "order_date",
    "ship_date",
    "ship_mode",
    "customer_id",
    "product_id",
    "postal_code",
    "sales",
    "quantity",
    "discount",
    "profit"
]

In [103]:
orders["order_date"] = pd.to_datetime(
    orders["order_date"]
)

orders["ship_date"] = pd.to_datetime(
    orders["ship_date"]
)

In [104]:
orders.to_sql(
    "orders",
    engine,
    if_exists="append",
    index=False,
    chunksize=1000
)

9994

In [105]:
pd.read_sql(
    "SELECT COUNT(*) AS cnt FROM orders;",
    engine
)

    cnt
0  9994