In [22]:
pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in /Users/piyushisinghal/Library/Python/3.9/lib/python/site-packages (2.0.51)
Requirement already satisfied: pymysql in /Users/piyushisinghal/Library/Python/3.9/lib/python/site-packages (1.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/piyushisinghal/Library/Python/3.9/lib/python/site-packages (from sqlalchemy) (4.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [23]:
from sqlalchemy import create_engine
import pandas as pd
from urllib.parse import quote_plus

In [24]:
password = quote_plus("@1a23456Z7")   # your actual password

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/retailiq"
)

In [25]:
print(engine.url)

mysql+pymysql://root:***@localhost:3306/retailiq

In [26]:
import pandas as pd

pd.read_sql(
    "SELECT DATABASE() AS current_db;",
    engine
)

  current_db
0   retailiq

In [27]:
from sqlalchemy import text

with engine.connect() as conn:

    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS customers(
            customer_id VARCHAR(20) PRIMARY KEY,
            customer_name VARCHAR(100),
            segment VARCHAR(50),
            region VARCHAR(50)
        )
    """))

    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS products(
            product_id VARCHAR(30) PRIMARY KEY,
            product_name VARCHAR(255),
            category VARCHAR(50),
            sub_category VARCHAR(50)
        )
    """))

    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS geography(
            postal_code INT PRIMARY KEY,
            city VARCHAR(100),
            state VARCHAR(100),
            region VARCHAR(50),
            country VARCHAR(50)
        )
    """))

    conn.commit()

print("Tables created")

Tables created

In [28]:
pd.read_sql(
    "SHOW TABLES;",
    engine
)

  Tables_in_retailiq
0          customers
1          geography
2           products